# Generated by Django 4.1.5 on 2023-01-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('projectImg', models.ImageField(blank=True, upload_to='images/projects')),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
